(specifications->manifest
 '("openjdk"
   "openjdk:doc"
   "node"
   "clojure"
   "clojure-tools"
   "gcc-toolchain"
   "gcc-toolchain:static"
   "emacs"
   "emacs-cider"
   "emacs-helm-cider"
   "emacs-typescript-mode"))
