DOCKER_IMAGE="crystallang/crystal:1.4.0-alpine"
def docker(arg)
 sh "docker run --rm -ti -u #{Process.uid} -v #{Dir.pwd}:/usr/app -w /usr/app #{DOCKER_IMAGE} #{arg}"
end

desc "shards[arguments] in container"
task :shards, :arg do |_, args|
  docker "shards #{args.arg}"
end

file 'bin/core.js' => ['core/core.ts'] do
  # first run npm install
  sh "node ./node_modules/.bin/tsc"
end

desc "test in container"
task :test => ['bin/core.js'] do
  docker "crystal spec spec/agent_core_spec.cr --error-trace"
end


